version: '3.1'

services:
  mysql-3307:
    image: mysql:5.7.22
    container_name: mysql-3307
    volumes:
      - /Users/mac/mysql-cluster/3307:/var/lib/mysql
      - /Users/mac/mysql-cluster/my3307.cnf:/etc/mysql/my.cnf
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci,--init_connect='SET NAMES utf8mb4', --explicit_defaults_for_timestamp=1]
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: test
    ports: 
      - "3307:3306"

  mysql-3308:
    image: mysql:5.7.22
    container_name: mysql-3308
    volumes:
      - /Users/mac/mysql-cluster/3308:/var/lib/mysql
      - /Users/mac/mysql-cluster/my3308.cnf:/etc/mysql/my.cnf
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci,--init_connect='SET NAMES utf8mb4', --explicit_defaults_for_timestamp=1]
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root2
      MYSQL_DATABASE: test
    ports: 
      - "3308:3306"
